import {supabase}from'../lib/supabase';import type{LocalPost,LocalUser}from'./types';import type{LocalNotification}from'./notifications';import{mapPost,mapUser,postSelect,throwIf,topicId}from'./supabase-helpers';
export async function getAdminOverview(){const names=['blugbug_users','blugbug_posts','blugbug_notifications','blugbug_support_cases'];const counts=await Promise.all(names.map(n=>supabase.from(n).select('*',{count:'exact',head:true})));counts.forEach(x=>throwIf(x.error));return{users:counts[0].count||0,posts:counts[1].count||0,notifications:counts[2].count||0,supportCases:counts[3].count||0}}
export async function listAdminUsers(){const{data,error}=await supabase.from('blugbug_users').select('*').order('created_at',{ascending:false});throwIf(error);return{users:(data??[]).map(mapUser)}}
export async function listAdminPosts(){const{data,error}=await supabase.from('blugbug_posts').select(postSelect).order('created_at',{ascending:false});throwIf(error);return{posts:(data??[]).map(mapPost)}}
export async function listAdminNotifications(){const{data,error}=await supabase.from('blugbug_notifications').select('*').order('created_at',{ascending:false});throwIf(error);return{notifications:(data??[]).map((x:any)=>({...x,read:Boolean(x.read)})) as LocalNotification[]}}
export async function adminDeleteUser(id:string){const{error}=await supabase.from('blugbug_users').delete().eq('id',id);throwIf(error)}
export async function adminDeleteNotification(id:string){const{error}=await supabase.from('blugbug_notifications').delete().eq('id',id);throwIf(error)}
export type AdminChannel=LocalUser&{post_count:number;posts:LocalPost[]};
export async function listAdminChannels(){const{data,error}=await supabase.from('blugbug_users').select('*').eq('account_type','channel').order('full_name');throwIf(error);const channels:AdminChannel[]=await Promise.all((data??[]).map(async row=>{const{posts}=await listPostsFor(row.id);return{...mapUser(row),post_count:posts.length,posts}}));return{channels}}
async function listPostsFor(id:string){const{data,error}=await supabase.from('blugbug_posts').select(postSelect).eq('user_id',id).order('created_at',{ascending:false});throwIf(error);return{posts:(data??[]).map(mapPost)}}
export async function adminUpdateChannel(id:string,body:Pick<LocalUser,'full_name'|'chatter_name'|'about_me'>){const{data,error}=await supabase.from('blugbug_users').update(body).eq('id',id).select().single();throwIf(error);return{channel:mapUser(data)}}
export async function adminCreateChannelPost(id:string,body:Pick<LocalPost,'title'|'content'|'categories'>){const topic_id=await topicId(body.categories);const{data,error}=await supabase.from('blugbug_posts').insert({user_id:id,topic_id,title:body.title,content_html:body.content,status:'published',published_at:new Date().toISOString(),reply_permission:'everyone'}).select(postSelect).single();throwIf(error);return{post:mapPost(data)}}
export async function adminUpdateChannelPost(channelId:string,postId:string,body:Pick<LocalPost,'title'|'content'|'categories'>){const topic_id=await topicId(body.categories);const{data,error}=await supabase.from('blugbug_posts').update({title:body.title,content_html:body.content,topic_id}).eq('id',postId).eq('user_id',channelId).select(postSelect).single();throwIf(error);return{post:mapPost(data)}}
