import { supabase } from '../lib/supabase';
import type { LocalPost } from './types';
import { currentProfileId,mapPost,postSelect,throwIf,topicId } from './supabase-helpers';

export const listPosts=async(userId?:string,feed?:'following')=>{let query=supabase.from('blugbug_posts').select(postSelect).order('created_at',{ascending:false});if(userId)query=query.eq('user_id',userId);else query=query.eq('status','published');if(feed){const me=await currentProfileId();const{data:follows,error:fError}=await supabase.from('blugbug_follows').select('followed_id').eq('follower_id',me);throwIf(fError);const ids=(follows||[]).map(x=>x.followed_id);if(!ids.length)return{posts:[]};query=query.in('user_id',ids)}const{data,error}=await query;throwIf(error);return{posts:(data||[]).map(mapPost)}};
const findPost=async(id:string,publishedOnly=false)=>{let query=supabase.from('blugbug_posts').select(postSelect);if(/^[0-9a-f-]{36}$/i.test(id))query=query.eq('id',id);else query=query.eq('legacy_id',id);if(publishedOnly)query=query.eq('status','published');const{data,error}=await query.single();throwIf(error);return{post:mapPost(data)}};
export const getPost=(id:string)=>findPost(id,false);export const getPublicPost=(id:string)=>findPost(id,true);
export const createPost=async(post:Pick<LocalPost,'title'|'content'>&Partial<LocalPost>)=>{const user_id=await currentProfileId();const topic_id=await topicId(post.categories),status=post.status||'published';const{data,error}=await supabase.from('blugbug_posts').insert({user_id,topic_id,title:post.title,content_html:post.content,status,published_at:status==='published'?new Date().toISOString():null,reply_permission:'everyone'}).select(postSelect).single();throwIf(error);return{post:mapPost(data)}};
export const updatePost=async(id:string,post:Partial<LocalPost>)=>{const changes:any={};if(post.title!==undefined)changes.title=post.title;if(post.content!==undefined)changes.content_html=post.content;if(post.status!==undefined){changes.status=post.status;if(post.status==='published')changes.published_at=new Date().toISOString()}if(post.header_image_url!==undefined)changes.cover_image_url=post.header_image_url;if(post.categories!==undefined)changes.topic_id=await topicId(post.categories);const{data,error}=await supabase.from('blugbug_posts').update(changes).eq('id',id).select(postSelect).single();throwIf(error);return{post:mapPost(data)}};
export const deletePost=async(id:string)=>{const{error}=await supabase.from('blugbug_posts').delete().eq('id',id);throwIf(error)};
