import { supabase } from '../lib/supabase';
import { currentProfileId, throwIf } from './supabase-helpers';
const ext=(f:File)=>f.name.split('.').pop()?.toLowerCase()||f.type.split('/')[1]||'jpg';
const url=(bucket:string,path:string)=>supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl;
export async function uploadImage(image:File,purpose:'profile'|'header',postId?:string,userId?:string){const owner=userId||await currentProfileId();const cover=Boolean(postId),bucket=cover?'blugbug_post_covers':purpose==='profile'?'blugbug_profiles':'blugbug_headers';const path=cover?`${owner}/${postId}/cover-${crypto.randomUUID()}.${ext(image)}`:`${owner}/${purpose}-${crypto.randomUUID()}.${ext(image)}`;const{error}=await supabase.storage.from(bucket).upload(path,image,{contentType:image.type});throwIf(error);const public_url=url(bucket,path);const q=cover?supabase.from('blugbug_posts').update({cover_image_url:public_url}).eq('id',postId!).eq('user_id',owner):supabase.from('blugbug_users').update({[purpose==='profile'?'profile_image_url':'header_image_url']:public_url}).eq('id',owner);const{error:e}=await q;throwIf(e);return{url:public_url}}
export type PendingInlineMedia={token:string;file:File;previewUrl:string;altText:string;caption:string};
export type UploadedPostMedia={id:string;post_id:string;public_url:string;alt_text:string;caption:string;mime_type:string;byte_size:number};
export async function uploadPostMedia(postId:string,p:PendingInlineMedia){const user_id=await currentProfileId(),path=`${user_id}/${postId}/${crypto.randomUUID()}.${ext(p.file)}`;const{error}=await supabase.storage.from('blugbug_post_media').upload(path,p.file,{contentType:p.file.type});throwIf(error);const{data,error:e}=await supabase.from('blugbug_post_media').insert({post_id:postId,user_id,storage_path:path,alt_text:p.altText.trim()||'Blug image',caption:p.caption.trim(),mime_type:p.file.type,byte_size:p.file.size}).select().single();throwIf(e);return{media:{...data,public_url:url('blugbug_post_media',path)} as UploadedPostMedia}}
export const pendingTokensInHtml=(html:string)=>{const b=new DOMParser().parseFromString(html,'text/html').body;return new Set([...b.querySelectorAll<HTMLElement>('figure[data-upload-token]')].map(n=>n.dataset.uploadToken||''))};
export const contentWithoutPendingMedia=(html:string)=>{const b=new DOMParser().parseFromString(html,'text/html').body;b.querySelectorAll('figure[data-upload-token]').forEach(n=>n.remove());return b.innerHTML};
export const resolvePendingMedia=(html:string,u:Map<string,UploadedPostMedia>)=>{const b=new DOMParser().parseFromString(html,'text/html').body;b.querySelectorAll<HTMLElement>('figure[data-upload-token]').forEach(f=>{const m=u.get(f.dataset.uploadToken||'');if(!m){f.remove();return}f.removeAttribute('data-upload-token');f.dataset.mediaId=m.id;f.removeAttribute('contenteditable');const i=f.querySelector('img');if(i){i.src=m.public_url;i.alt=m.alt_text;i.loading='lazy'}});return b.innerHTML};
