<template>
  <div class="page-shell"><NavBar /><main v-if="user" class="profile-page"><PageColumns>
    <section class="profile-hero surface">
      <div class="cover" :style="coverStyle"><div class="cover-pattern"></div><label v-if="isMe&&user.recovery_status!=='pending'" class="upload">Change header<input type="file" hidden accept="image/*" @change="upload($event, 'header')" /></label></div>
      <div class="profile-row"><div class="portrait"><img v-if="user.profile_image_url" :src="user.profile_image_url" alt="Profile picture" /><span v-else>{{ initials }}</span><label v-if="isMe&&user.recovery_status!=='pending'" class="camera"><span aria-hidden="true">+</span><span class="sr-only">Change profile picture</span><input type="file" hidden accept="image/*" @change="upload($event, 'profile')" /></label></div><div class="identity"><span class="eyebrow">Blugger profile</span><h1>{{ user.full_name }}</h1><p>@{{ user.chatter_name }}</p><small v-if="isMe&&user.recovery_status==='pending'">Pending approval</small></div><button v-if="!isMe" class="primary-button" @click="toggleFollow">{{ status.following ? 'Following' : 'Follow' }}</button><button v-else class="ghost-button" @click="router.push('/settings')">Edit profile</button></div>
      <div class="profile-bottom"><p>{{ user.about_me || 'Writing thoughts, finding people, starting conversations.' }}</p><div><b>{{ posts.length }}</b><span>Blugs</span><b>{{ status.followers }}</b><span>Followers</span><b>{{ status.followingCount }}</b><span>Following</span></div></div>
    </section>
    <div class="profile-content"><section><div class="section-head"><div><span class="eyebrow">Published work</span><h2>Latest blugs</h2></div><button v-if="isMe" class="primary-button" @click="router.push('/create-blog')">＋ New blug</button></div><LocalPostCard v-for="post in posts" :key="post.id" :post="post" /></section></div>
    <template #right><aside class="surface profile-about"><span class="eyebrow">About this voice</span><h3>Interests</h3><div class="chips"><span v-for="topic in topics" :key="topic">{{ topic }}</span></div><hr /><p class="muted">Member since {{ new Date(user.created_at).toLocaleDateString('en', { month: 'long', year: 'numeric' }) }}</p></aside></template>
  </PageColumns></main></div>
</template>
<script setup lang="ts">
import PageColumns from './PageColumns.vue';
import { computed, onMounted, reactive, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import NavBar from './NavBar.vue'; import LocalPostCard from './LocalPostCard.vue'; import { getUser } from '../api/users'; import { listPosts } from '../api/posts'; import { getFollowStatus, setFollowing } from '../api/social'; import { uploadImage } from '../api/uploads'; import { authStore } from '../stores/auth'; import type { LocalUser, LocalPost } from '../api/types';
const route=useRoute(),router=useRouter(),user=ref<LocalUser|null>(null),posts=ref<LocalPost[]>([]),status=reactive({following:false,followers:0,followingCount:0}); const isMe=computed(()=>user.value?.id===authStore.user.value?.id),initials=computed(()=>(user.value?.full_name||'BB').split(' ').map(x=>x[0]).slice(0,2).join('')),coverStyle=computed(()=>user.value?.header_image_url?{backgroundImage:`linear-gradient(0deg,rgba(10,12,15,.35),transparent),url(${user.value.header_image_url})`}:{}),topics=computed(()=>[...new Set(posts.value.map(p=>p.categories).filter(Boolean))].slice(0,6)); const load=async()=>{const id=String(route.params.userId);user.value=(await getUser(id)).user;posts.value=(await listPosts(id)).posts;Object.assign(status,await getFollowStatus(id))}; const toggleFollow=async()=>{if(!user.value)return;await setFollowing(user.value.id,!status.following);await load()}; const upload=async(e:Event,purpose:'profile'|'header')=>{const input=e.target as HTMLInputElement;const file=input.files?.[0];if(file){const {url}=await uploadImage(file,purpose);if(user.value)user.value={...user.value,[purpose==='header'?'header_image_url':'profile_image_url']:url};await authStore.refresh();await load();input.value=''}}; onMounted(load);
</script>
<style scoped>
.profile-page{width:min(1120px,calc(100% - 32px));margin:0 auto;padding:32px 0 90px}.profile-hero{overflow:hidden}.cover{height:250px;position:relative;background:#252a31;background-size:cover;background-position:center}.cover-pattern{position:absolute;inset:0}.upload{position:absolute;right:20px;bottom:18px;padding:9px 13px;border:1px solid rgba(255,255,255,.28);border-radius:999px;background:rgba(12,14,17,.9);color:#fff!important;font-size:.75rem;font-weight:800;cursor:pointer;text-shadow:0 1px 2px #000}.upload:hover{background:#0c0e11}.profile-row{display:flex;align-items:end;gap:20px;padding:0 28px;transform:translateY(-35px);margin-bottom:-24px}.portrait{position:relative;display:grid;place-items:center;flex:0 0 126px;height:126px;border:5px solid var(--panel);border-radius:50%;background:var(--orange);color:#fff;font:800 2rem Georgia}.portrait img{width:100%;height:100%;border-radius:50%;object-fit:cover}.camera{position:absolute;right:0;bottom:5px;display:grid;place-items:center;width:36px;height:36px;padding:0;border-radius:50%;background:var(--orange);color:#fff!important;border:3px solid var(--panel);cursor:pointer;font:900 1.35rem/1 Inter,ui-sans-serif,system-ui}.camera>span:first-child{display:block;width:1em;height:1em;line-height:.92;text-align:center;transform:none}.identity{flex:1;padding-bottom:8px}.identity h1{font:700 2.2rem Georgia;margin:5px 0 2px;color:var(--text)}.identity p{margin:0;color:var(--muted)}.profile-row>button{margin-bottom:12px}.profile-bottom{display:flex;justify-content:space-between;align-items:center;padding:0 28px 25px;gap:30px}.profile-bottom>p{max-width:570px;color:var(--muted);line-height:1.6}.profile-bottom>div{display:grid;grid-template-columns:auto auto;gap:3px 9px}.profile-bottom b{color:var(--text)}.profile-bottom span{color:var(--muted);font-size:.78rem}.profile-content{display:grid;grid-template-columns:minmax(0,1fr) 280px;gap:26px;margin-top:30px}.section-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:18px}.section-head h2{font:700 2rem Georgia;margin:6px 0 0}.profile-content aside{align-self:start;padding:22px}.profile-content aside h3{margin:8px 0 12px;font:700 1.15rem/1.2 Georgia,serif}.chips{display:flex;flex-wrap:wrap;gap:7px}.chips span{padding:7px 10px;border:1px solid var(--line);border-radius:99px;background:var(--soft);color:var(--text);font-size:.76rem}.profile-content hr{border:0;border-top:1px solid var(--line);margin:20px 0}
.portrait img{position:absolute;inset:0;display:block;width:100%;height:100%;border-radius:50%;object-fit:cover;object-position:center;clip-path:circle(50% at 50% 50%)}
@media(max-width:780px){.cover{height:170px}.profile-content{display:block}.profile-content aside{display:none}}
@media(max-width:520px){.profile-page{width:100%;padding:0 0 88px}.profile-hero{border-left:0;border-right:0;border-radius:0}.cover{height:126px}.upload{right:12px;bottom:10px;padding:7px 10px;font-size:.65rem}.profile-row{display:grid;grid-template-columns:82px minmax(0,1fr);grid-template-rows:auto auto;align-items:end;column-gap:14px;row-gap:7px;padding:0 16px 14px;transform:none;margin:0}.portrait{grid-column:1;grid-row:1/3;align-self:start;flex-basis:auto;width:82px;height:82px;margin-top:-34px;border-width:4px}.camera{right:-2px;bottom:0;width:29px;height:29px;border-width:2px}.identity{grid-column:2;grid-row:1;min-width:0;padding:10px 0 0;margin:0}.identity .eyebrow{font-size:.58rem}.identity h1{margin:4px 0 1px;font-size:1.48rem;line-height:1.05;overflow-wrap:anywhere}.identity p{font-size:.78rem}.profile-row>button{grid-column:2;grid-row:2;align-self:start;justify-self:start;margin:0;padding:7px 11px;font-size:.67rem}.profile-bottom{display:block;padding:0 16px 18px}.profile-bottom>p{margin:0 0 14px;font-size:.83rem;line-height:1.45}.profile-bottom>div{display:grid;grid-template-columns:repeat(3,1fr);gap:2px 12px;padding-top:12px;border-top:1px solid var(--line)}.profile-bottom b{grid-row:1;font-size:1rem}.profile-bottom span{grid-row:2;font-size:.65rem}.profile-bottom b:nth-of-type(1),.profile-bottom span:nth-of-type(1){grid-column:1}.profile-bottom b:nth-of-type(2),.profile-bottom span:nth-of-type(2){grid-column:2}.profile-bottom b:nth-of-type(3),.profile-bottom span:nth-of-type(3){grid-column:3}.profile-content{margin-top:0}.section-head{align-items:center;padding:18px 14px 10px;margin:0}.section-head .eyebrow{font-size:.58rem}.section-head h2{margin-top:4px;font-size:1.55rem;line-height:1}.section-head .primary-button{padding:8px 11px;font-size:.7rem;white-space:nowrap}}
@media(max-width:520px){.portrait .camera{right:4px;bottom:4px;width:27px;height:27px;border-width:2px;font-size:.9rem;line-height:1}}
.profile-page{width:100%;max-width:none}.profile-content{display:block}.profile-about{padding:18px!important}.profile-about h3{margin:8px 0 12px}
</style>
