<template>
  <main class="login-page"><section class="login-shell"><div class="mascot-panel"><img class="brand-logo" src="/brand_logo.svg" alt="Blugbug" /><div class="mascot-copy"><img class="mascot" src="/Signinsvg.svg" alt="Blugbug mascot writing on a laptop" /><h2>Welcome to Blugbug</h2><p>Connect with people, share your thoughts, and discover ideas worth discussing. Happy Blugging!</p></div></div><div class="form-panel"><form class="login-card" @submit.prevent="submit"><img class="logo-mark" src="/icon_1-01.png" alt="Blugbug logo" /><h1>Login</h1><label><span>Email</span><input v-model="username" type="email" autocomplete="email" placeholder="Email address" required /></label><label><span>Password</span><input v-model="password" type="password" autocomplete="current-password" placeholder="Password" required /></label><div class="help-row"><router-link to="/recover-account">Recover old account</router-link><router-link to="/support">Help</router-link></div><p v-if="error" class="error">{{ error }}</p><button class="login-button" :disabled="loading">{{ loading ? 'Logging in…' : 'Login' }}</button><small>Returning from the old Blugbug? Recover your profile using its email.</small></form></div></section></main>
</template>
<script setup lang="ts">import{ref}from'vue';import{useRoute,useRouter}from'vue-router';import{authStore}from'../stores/auth';const route=useRoute(),router=useRouter(),username=ref(''),password=ref(''),loading=ref(false),error=ref('');const submit=async()=>{loading.value=true;error.value='';try{await authStore.login(username.value,password.value);await router.push(typeof route.query.redirect==='string'?route.query.redirect:'/home')}catch(e){error.value=e instanceof Error?e.message:'Could not sign in.'}finally{loading.value=false}};</script>
<style scoped>
.login-page{min-height:100vh;display:grid;place-items:center;padding:32px;background:#454b52}.login-shell{width:min(1120px,78vw);min-height:720px;display:grid;grid-template-columns:1fr 1fr;overflow:hidden;border:5px solid #0c1118;border-radius:20px;background:#1e2127;box-shadow:0 8px 22px rgba(0,0,0,.65)}.mascot-panel{position:relative;display:grid;place-items:center;padding:70px 42px 30px;background:#1e2127}.brand-logo{position:absolute;top:34px;left:38px;width:170px}.mascot{width:min(88%,520px);max-height:530px;object-fit:contain}.form-panel{display:grid;place-items:center;padding:48px;background:#2b3138}.login-card{width:min(400px,100%);min-height:560px;display:flex;flex-direction:column;justify-content:center;padding:40px;border-radius:12px;background:#293038;box-shadow:0 4px 12px rgba(0,0,0,.16)}.logo-mark{width:48px;height:48px;margin:0 auto 20px;border-radius:50%;object-fit:cover}.login-card h1{margin:0 0 34px;color:#d7c9b7;text-align:center;font-size:1.6rem}.login-card label{display:grid;gap:8px;margin-bottom:18px;color:#a9adb2;font-size:.75rem}.login-card input{width:100%;padding:13px 15px;border:0;border-bottom:1px solid #58606a;background:transparent;color:#f3eee8;outline:none}.login-card input:focus{border-color:var(--orange)}.help-row{display:flex;justify-content:space-between;margin:2px 0 14px}.help-row a{color:var(--orange);font-size:.82rem;font-weight:700}.login-button{width:100%;padding:12px;border:0;border-radius:999px;background:var(--orange);color:white;font-weight:800;cursor:pointer}.login-card small{margin-top:22px;color:#8b929b;text-align:center}.error{margin:0 0 12px;color:#ff806b;font-size:.8rem}@media(max-width:900px){.login-shell{width:min(94vw,680px);grid-template-columns:1fr}.mascot-panel{min-height:270px;padding:60px 20px 15px}.mascot{height:210px}.brand-logo{top:18px;left:22px;width:128px}.form-panel{padding:24px}.login-card{min-height:auto;padding:28px}}@media(max-width:520px){.login-page{padding:0;background:#2b3138}.login-shell{width:100%;min-height:100vh;border:0;border-radius:0;display:block}.mascot-panel{display:none}.form-panel{min-height:100vh}.login-card{box-shadow:none}}
.mascot-copy{text-align:center}.mascot-copy h2{margin:8px 0;color:var(--orange);font-size:2rem}.mascot-copy p{max-width:470px;margin:0 auto;color:#d7c9b7;line-height:1.5}
.login-page{background:#f3eee5}.login-shell{border:1px solid #d8cdbc;background:#fffaf0;box-shadow:0 18px 50px rgba(55,43,29,.14)}.mascot-panel{background:#fffaf0}.form-panel{background:#f8f0e3}.login-card{background:#fffaf0;border:1px solid #ded2c0;box-shadow:0 12px 30px rgba(55,43,29,.1)}.login-card h1{color:#201d19}.login-card label{color:#625c54}.login-card input{border-color:#cbbda8;color:#201d19}.login-card small{color:#625c54}.mascot-copy h2{color:#d62828}.mascot-copy p{color:#625c54}.login-button{border-radius:10px;background:#d62828}@media(max-width:520px){.login-page,.form-panel{background:#f3eee5}.login-shell{background:#f3eee5}}
</style>
