CREATE TABLE IF NOT EXISTS import_drafts (
  id TEXT PRIMARY KEY,
  source_url TEXT NOT NULL UNIQUE,
  source_title TEXT NOT NULL DEFAULT '',
  channel_id TEXT NOT NULL,
  topic TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  cover_image_url TEXT,
  status TEXT NOT NULL DEFAULT 'ready' CHECK (status IN ('draft', 'ready', 'published', 'rejected')),
  published_post_id TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS import_drafts_status_idx ON import_drafts(status, created_at DESC);

INSERT OR IGNORE INTO import_drafts (id, source_url, source_title, channel_id, topic, title, content, status) VALUES
('import-nairaland-8734128', 'https://www.nairaland.com/8734128/atiku-restoring-fuel-subsidy-outright', 'Atiku Restoring Fuel Subsidy Is Outright Deception To Win Election – Shehu Sani', 'channel-election-ng', 'Elections', 'Fuel Subsidy Returns to the 2027 Campaign—But What Exactly Is Being Promised?', '<p>Fuel subsidy has returned to Nigeria’s political conversation, this time as an election promise and a test of credibility. Former Kaduna Central senator Shehu Sani has criticised Atiku Abubakar’s reported proposal to restore subsidy, describing the reversal as an attempt to win votes rather than a workable economic plan.</p><p>Sani’s argument rests on Atiku’s previous support for subsidy removal and other market-oriented policies. In his view, a candidate who has long backed privatisation, currency reform and reduced government intervention must explain clearly why his position has changed—and how a restored subsidy would avoid the corruption and disputed payments associated with earlier programmes.</p><h2>The hardship cannot be ignored</h2><p>That criticism does not erase the pressure Nigerians are experiencing. The removal of fuel subsidy raised transport and operating costs across the economy, and households have felt the effect through food prices, commuting expenses and the cost of running small businesses. Even critics of restoration acknowledge that the policy transition has caused severe hardship.</p><p>The real question is therefore larger than whether subsidy should simply return. Voters need to know what would be subsidised, who would qualify, how the cost would be funded, how fraud would be prevented and what timetable would apply. A slogan cannot answer those questions.</p><h2>What the public discussion reveals</h2><p>Responses to the report divided sharply. Some contributors treated the proposal as another campaign promise from a desperate political class. Others argued that governments routinely subsidise essential sectors and that Nigerians should judge any proposal by whether it reduces the burden on ordinary people. Several asked for a specific implementation plan rather than another argument about personalities.</p><p>That is the useful standard for every candidate: publish the numbers, name the beneficiaries, explain the safeguards and show how the policy fits into the wider budget. Whether the answer is a targeted transport subsidy, direct household support, cheaper public transit or another model, Nigerians deserve more than the words “remove” and “restore.”</p><p><em>Source discussion: Nairaland Politics. The original report linked by the thread was published by Daily Post. This Blug is an independent summary and analysis, not a reproduction of either article.</em></p>', 'ready'),
('import-nairaland-8733365', 'https://www.nairaland.com/8733365/obi-challenges-presidential-candidates-face', 'Obi Challenges Presidential Candidates To Face Nigerians, Defend Their Records', 'channel-election-ng', 'Elections', 'The 2027 Candidates Want Our Votes—Let Them Defend Their Records in Public', '<p>Peter Obi has challenged Nigeria’s presidential candidates to face citizens directly, defend their records and submit their plans to public scrutiny ahead of the 2027 election. The proposal is simple: anyone asking to lead the country should be willing to answer difficult questions without relying entirely on campaign spokespeople, supporters or carefully edited publicity.</p><p>At the launch of his campaign, Obi framed leadership as a combination of presence and empathy. He argued that candidates should visit communities affected by insecurity, flooding and economic hardship, listen to the people living through those conditions and explain what they would do differently.</p><h2>Campaign promises need measurable details</h2><p>Obi’s stated priorities include security, education, healthcare, agriculture, manufacturing, technology, energy and a shift from consumption toward production. Those themes are familiar in Nigerian campaigns. Their value will depend on the details: funding, timelines, responsible institutions, measurable targets and an honest account of the trade-offs.</p><p>A public debate should therefore go beyond rehearsed speeches. Candidates could be asked to defend decisions from previous offices, explain disputed claims, identify policies they would reverse, show how their budgets add up and state what success should look like after one year and after four.</p><h2>Records matter, but scrutiny must apply to everyone</h2><p>The forum discussion showed why a neutral standard is necessary. Supporters praised their preferred candidates’ records while opponents questioned credentials, past performance and political alliances. Others argued that academic qualifications alone do not guarantee competent government. Beneath the insults was a reasonable demand: no candidate should choose which parts of their history the public is allowed to examine.</p><p>Public scrutiny is not a punishment reserved for one party. It is the job interview for the presidency. Debates, town halls, independent fact-checks and accessible policy documents would give voters something stronger than slogans and fan loyalty.</p><p>Democracy also continues after election day. A candidate who asks opponents to answer questions must remain available for questions after taking office. The strongest version of this challenge is therefore a promise to make accountability routine, regardless of who wins.</p><p><em>Source discussion: Nairaland Politics. The report shared in the thread originated from Channels Television. This Blug is an independent summary and analysis, not a reproduction of either article.</em></p>', 'ready');
