-- Blugbug / Supabase foundation
-- Safe for a Supabase project shared with other applications:
-- every application-owned table, function, trigger, policy and bucket is prefixed blugbug_.
-- Run this entire file once in Supabase Dashboard -> SQL Editor.

begin;

create schema if not exists blugbug_private;
revoke all on schema blugbug_private from public, anon, authenticated;

-- PUBLIC IDENTITY -------------------------------------------------------------

create table if not exists public.blugbug_users (
  id text primary key default gen_random_uuid()::text,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  username text not null,
  chatter_name text not null,
  full_name text not null,
  about_me text not null default '',
  profile_image_url text,
  header_image_url text,
  account_type text not null default 'person'
    check (account_type in ('person', 'channel')),
  account_status text not null default 'active'
    check (account_status in ('active', 'suspended', 'deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint blugbug_users_username_length check (char_length(username) between 2 and 60),
  constraint blugbug_users_handle_format check (chatter_name ~ '^[A-Za-z0-9._-]{2,40}$'),
  constraint blugbug_users_name_length check (char_length(full_name) between 1 and 100),
  constraint blugbug_users_bio_length check (char_length(about_me) <= 500),
  constraint blugbug_users_channel_auth check (account_type <> 'channel' or auth_user_id is null)
);

create unique index if not exists blugbug_users_username_lower_uidx
  on public.blugbug_users (lower(username));
create unique index if not exists blugbug_users_chatter_name_lower_uidx
  on public.blugbug_users (lower(chatter_name));
create index if not exists blugbug_users_auth_user_idx
  on public.blugbug_users (auth_user_id) where auth_user_id is not null;
create index if not exists blugbug_users_discovery_idx
  on public.blugbug_users (account_status, account_type, created_at desc);

-- Kept separate from public profiles. Only SQL Editor / trusted backend code
-- should ever read or write this table.
create table if not exists public.blugbug_admins (
  auth_user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.blugbug_topics (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  description text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint blugbug_topics_slug_format check (slug ~ '^[a-z0-9-]{2,60}$'),
  constraint blugbug_topics_name_length check (char_length(name) between 2 and 80)
);

insert into public.blugbug_topics (slug, name) values
  ('life', 'Life'), ('culture', 'Culture'), ('tech', 'Tech'),
  ('travel', 'Travel'), ('food', 'Food'), ('creativity', 'Creativity'),
  ('finance', 'Finance'), ('wellness', 'Wellness'), ('books', 'Books'),
  ('community', 'Community'), ('sports', 'Sports'), ('film', 'Film'),
  ('history', 'History'), ('society', 'Society'), ('music', 'Music'),
  ('politics', 'Politics'), ('elections', 'Elections')
on conflict (slug) do nothing;

create table if not exists public.blugbug_user_interests (
  user_id text not null references public.blugbug_users(id) on delete cascade,
  topic_id bigint not null references public.blugbug_topics(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, topic_id)
);

-- BLUGS ----------------------------------------------------------------------

create table if not exists public.blugbug_series (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references public.blugbug_users(id) on delete cascade,
  title text not null,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint blugbug_series_title_length check (char_length(title) between 1 and 180),
  constraint blugbug_series_description_length check (char_length(description) <= 500)
);

create table if not exists public.blugbug_posts (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  user_id text not null references public.blugbug_users(id) on delete cascade,
  topic_id bigint references public.blugbug_topics(id) on delete set null,
  series_id uuid references public.blugbug_series(id) on delete set null,
  part_number smallint,
  title text not null,
  content_html text not null default '',
  excerpt text not null default '',
  cover_image_url text,
  status text not null default 'draft'
    check (status in ('draft', 'published', 'archived')),
  reply_permission text not null default 'everyone'
    check (reply_permission in ('everyone', 'followers', 'nobody')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint blugbug_posts_title_length check (char_length(title) between 1 and 180),
  constraint blugbug_posts_excerpt_length check (char_length(excerpt) <= 500),
  constraint blugbug_posts_part_number check (part_number is null or part_number > 0),
  constraint blugbug_posts_published_time check (status <> 'published' or published_at is not null)
);

create unique index if not exists blugbug_posts_series_part_uidx
  on public.blugbug_posts (series_id, part_number)
  where series_id is not null and part_number is not null;
create index if not exists blugbug_posts_author_created_idx
  on public.blugbug_posts (user_id, created_at desc);
create index if not exists blugbug_posts_public_feed_idx
  on public.blugbug_posts (published_at desc) where status = 'published';
create index if not exists blugbug_posts_topic_feed_idx
  on public.blugbug_posts (topic_id, published_at desc) where status = 'published';
create index if not exists blugbug_posts_title_search_idx
  on public.blugbug_posts using gin (to_tsvector('english', title || ' ' || excerpt));

-- SOCIAL GRAPH AND INTERACTIONS ----------------------------------------------

create table if not exists public.blugbug_follows (
  follower_id text not null references public.blugbug_users(id) on delete cascade,
  followed_id text not null references public.blugbug_users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, followed_id),
  check (follower_id <> followed_id)
);
create index if not exists blugbug_follows_followed_idx
  on public.blugbug_follows (followed_id, created_at desc);

create table if not exists public.blugbug_post_likes (
  post_id uuid not null references public.blugbug_posts(id) on delete cascade,
  user_id text not null references public.blugbug_users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);
create index if not exists blugbug_post_likes_user_idx
  on public.blugbug_post_likes (user_id, created_at desc);

create table if not exists public.blugbug_bookmarks (
  post_id uuid not null references public.blugbug_posts(id) on delete cascade,
  user_id text not null references public.blugbug_users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);
create index if not exists blugbug_bookmarks_user_idx
  on public.blugbug_bookmarks (user_id, created_at desc);

create table if not exists public.blugbug_post_shares (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.blugbug_posts(id) on delete cascade,
  user_id text references public.blugbug_users(id) on delete set null,
  destination text not null default 'copy_link',
  created_at timestamptz not null default now(),
  constraint blugbug_post_shares_destination_length check (char_length(destination) between 2 and 60)
);
create index if not exists blugbug_post_shares_post_idx
  on public.blugbug_post_shares (post_id, created_at desc);

create table if not exists public.blugbug_comments (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  post_id uuid not null references public.blugbug_posts(id) on delete cascade,
  user_id text not null references public.blugbug_users(id) on delete cascade,
  body text not null,
  status text not null default 'visible'
    check (status in ('visible', 'hidden', 'deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint blugbug_comments_body_length check (char_length(btrim(body)) between 1 and 2000)
);
create index if not exists blugbug_comments_post_idx
  on public.blugbug_comments (post_id, created_at);

create table if not exists public.blugbug_comment_replies (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  comment_id uuid not null references public.blugbug_comments(id) on delete cascade,
  user_id text not null references public.blugbug_users(id) on delete cascade,
  body text not null,
  status text not null default 'visible'
    check (status in ('visible', 'hidden', 'deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint blugbug_comment_replies_body_length check (char_length(btrim(body)) between 1 and 2000)
);
create index if not exists blugbug_comment_replies_comment_idx
  on public.blugbug_comment_replies (comment_id, created_at);

create table if not exists public.blugbug_paragraph_questions (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.blugbug_posts(id) on delete cascade,
  paragraph_index integer not null check (paragraph_index >= 0),
  user_id text not null references public.blugbug_users(id) on delete cascade,
  body text not null,
  status text not null default 'open' check (status in ('open', 'answered', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint blugbug_paragraph_questions_body_length check (char_length(btrim(body)) between 1 and 1000)
);
create index if not exists blugbug_paragraph_questions_post_idx
  on public.blugbug_paragraph_questions (post_id, paragraph_index, created_at);

create table if not exists public.blugbug_paragraph_answers (
  id uuid primary key default gen_random_uuid(),
  question_id uuid not null unique references public.blugbug_paragraph_questions(id) on delete cascade,
  user_id text not null references public.blugbug_users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint blugbug_paragraph_answers_body_length check (char_length(btrim(body)) between 1 and 2000)
);

-- ACTIVITY -------------------------------------------------------------------

create table if not exists public.blugbug_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references public.blugbug_users(id) on delete cascade,
  actor_id text references public.blugbug_users(id) on delete set null,
  type text not null check (type in (
    'follow', 'like', 'comment', 'reply', 'share', 'new_post',
    'paragraph_question', 'paragraph_answer', 'mention', 'system'
  )),
  message text not null,
  post_id uuid references public.blugbug_posts(id) on delete set null,
  read boolean not null default false,
  created_at timestamptz not null default now(),
  constraint blugbug_notifications_message_length check (char_length(message) between 1 and 500)
);
create index if not exists blugbug_notifications_inbox_idx
  on public.blugbug_notifications (user_id, read, created_at desc);

-- SUPPORT, SAFETY, AND RECOVERY ----------------------------------------------

create table if not exists public.blugbug_support_cases (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references public.blugbug_users(id) on delete cascade,
  subject text not null,
  status text not null default 'open' check (status in ('open', 'resolved', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint blugbug_support_cases_subject_length check (char_length(subject) between 1 and 180)
);
create index if not exists blugbug_support_cases_user_idx
  on public.blugbug_support_cases (user_id, updated_at desc);

create table if not exists public.blugbug_support_messages (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.blugbug_support_cases(id) on delete cascade,
  user_id text not null references public.blugbug_users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  constraint blugbug_support_messages_body_length check (char_length(btrim(body)) between 1 and 5000)
);
create index if not exists blugbug_support_messages_case_idx
  on public.blugbug_support_messages (case_id, created_at);

create table if not exists public.blugbug_blocks (
  blocker_id text not null references public.blugbug_users(id) on delete cascade,
  blocked_id text not null references public.blugbug_users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create table if not exists public.blugbug_reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id text not null references public.blugbug_users(id) on delete cascade,
  reported_user_id text references public.blugbug_users(id) on delete set null,
  post_id uuid references public.blugbug_posts(id) on delete set null,
  comment_id uuid references public.blugbug_comments(id) on delete set null,
  reason text not null,
  details text not null default '',
  status text not null default 'open' check (status in ('open', 'reviewing', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint blugbug_reports_target check (
    num_nonnulls(reported_user_id, post_id, comment_id) = 1
  ),
  constraint blugbug_reports_reason_length check (char_length(reason) between 2 and 100),
  constraint blugbug_reports_details_length check (char_length(details) <= 2000)
);
create index if not exists blugbug_reports_status_idx
  on public.blugbug_reports (status, created_at desc);

-- Never import old plaintext passwords into this table. Recovery verification
-- belongs in trusted backend / Edge Function code, never in the browser.
create table if not exists public.blugbug_legacy_accounts (
  user_id text primary key references public.blugbug_users(id) on delete cascade,
  legacy_email text,
  secret_question text,
  secret_answer_hash text,
  claimed_auth_user_id uuid unique references auth.users(id) on delete set null,
  claimed_at timestamptz,
  created_at timestamptz not null default now()
);
create unique index if not exists blugbug_legacy_accounts_email_lower_uidx
  on public.blugbug_legacy_accounts (lower(legacy_email)) where legacy_email is not null;

create table if not exists public.blugbug_recovery_requests (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references public.blugbug_users(id) on delete cascade,
  code_hash text not null,
  expires_at timestamptz not null,
  attempts smallint not null default 0 check (attempts between 0 and 10),
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists blugbug_recovery_requests_user_idx
  on public.blugbug_recovery_requests (user_id, expires_at desc);

-- SECURITY HELPERS -----------------------------------------------------------

create or replace function blugbug_private.current_profile_id()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select u.id
  from public.blugbug_users u
  where u.auth_user_id = (select auth.uid())
    and u.account_status = 'active'
  limit 1
$$;

create or replace function blugbug_private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.blugbug_admins a
    where a.auth_user_id = (select auth.uid())
  )
$$;

revoke all on function blugbug_private.current_profile_id() from public;
revoke all on function blugbug_private.is_admin() from public;
grant usage on schema blugbug_private to anon, authenticated;
grant execute on function blugbug_private.current_profile_id() to anon, authenticated;
grant execute on function blugbug_private.is_admin() to anon, authenticated;

create or replace function blugbug_private.touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function blugbug_private.prepare_post()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.status = 'published' and new.published_at is null then
    new.published_at = now();
  end if;
  return new;
end;
$$;

-- RLS ------------------------------------------------------------------------

alter table public.blugbug_users enable row level security;
alter table public.blugbug_admins enable row level security;
alter table public.blugbug_topics enable row level security;
alter table public.blugbug_user_interests enable row level security;
alter table public.blugbug_series enable row level security;
alter table public.blugbug_posts enable row level security;
alter table public.blugbug_follows enable row level security;
alter table public.blugbug_post_likes enable row level security;
alter table public.blugbug_bookmarks enable row level security;
alter table public.blugbug_post_shares enable row level security;
alter table public.blugbug_comments enable row level security;
alter table public.blugbug_comment_replies enable row level security;
alter table public.blugbug_paragraph_questions enable row level security;
alter table public.blugbug_paragraph_answers enable row level security;
alter table public.blugbug_notifications enable row level security;
alter table public.blugbug_support_cases enable row level security;
alter table public.blugbug_support_messages enable row level security;
alter table public.blugbug_blocks enable row level security;
alter table public.blugbug_reports enable row level security;
alter table public.blugbug_legacy_accounts enable row level security;
alter table public.blugbug_recovery_requests enable row level security;

-- Profiles
create policy "blugbug_users_public_read" on public.blugbug_users
  for select to anon, authenticated
  using (account_status = 'active' or id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_users_create_self" on public.blugbug_users
  for insert to authenticated
  with check (auth_user_id = (select auth.uid()) and account_type = 'person' and account_status = 'active');
create policy "blugbug_users_admin_create_channel" on public.blugbug_users
  for insert to authenticated
  with check ((select blugbug_private.is_admin()) and auth_user_id is null and account_type = 'channel');
create policy "blugbug_users_update_self_or_admin" on public.blugbug_users
  for update to authenticated
  using (id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()))
  with check (id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_users_admin_delete" on public.blugbug_users
  for delete to authenticated using ((select blugbug_private.is_admin()));

-- Topics and interests
create policy "blugbug_topics_public_read" on public.blugbug_topics
  for select to anon, authenticated using (is_active or (select blugbug_private.is_admin()));
create policy "blugbug_topics_admin_write" on public.blugbug_topics
  for all to authenticated using ((select blugbug_private.is_admin())) with check ((select blugbug_private.is_admin()));
create policy "blugbug_interests_public_read" on public.blugbug_user_interests
  for select to anon, authenticated using (true);
create policy "blugbug_interests_owner_write" on public.blugbug_user_interests
  for all to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()))
  with check (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));

-- Series and posts
create policy "blugbug_series_public_read" on public.blugbug_series
  for select to anon, authenticated using (
    user_id = (select blugbug_private.current_profile_id())
    or (select blugbug_private.is_admin())
    or exists (select 1 from public.blugbug_posts p where p.series_id = id and p.status = 'published')
  );
create policy "blugbug_series_owner_write" on public.blugbug_series
  for all to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()))
  with check (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_posts_visible_read" on public.blugbug_posts
  for select to anon, authenticated
  using (status = 'published' or user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_posts_owner_insert" on public.blugbug_posts
  for insert to authenticated
  with check (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_posts_owner_update" on public.blugbug_posts
  for update to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()))
  with check (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_posts_owner_delete" on public.blugbug_posts
  for delete to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));

-- Social data
create policy "blugbug_follows_public_read" on public.blugbug_follows for select to anon, authenticated using (true);
create policy "blugbug_follows_owner_insert" on public.blugbug_follows for insert to authenticated
  with check (follower_id = (select blugbug_private.current_profile_id()));
create policy "blugbug_follows_owner_delete" on public.blugbug_follows for delete to authenticated
  using (follower_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_likes_public_read" on public.blugbug_post_likes for select to anon, authenticated using (true);
create policy "blugbug_likes_owner_insert" on public.blugbug_post_likes for insert to authenticated
  with check (user_id = (select blugbug_private.current_profile_id()));
create policy "blugbug_likes_owner_delete" on public.blugbug_post_likes for delete to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_bookmarks_owner_read" on public.blugbug_bookmarks for select to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_bookmarks_owner_insert" on public.blugbug_bookmarks for insert to authenticated
  with check (user_id = (select blugbug_private.current_profile_id()));
create policy "blugbug_bookmarks_owner_delete" on public.blugbug_bookmarks for delete to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_shares_insert" on public.blugbug_post_shares for insert to authenticated
  with check (
    user_id = (select blugbug_private.current_profile_id())
    and exists (select 1 from public.blugbug_posts p where p.id = post_id and p.status = 'published')
  );
create policy "blugbug_shares_owner_or_admin_read" on public.blugbug_post_shares for select to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));

-- Discussion
create policy "blugbug_comments_public_read" on public.blugbug_comments for select to anon, authenticated
  using (
    (status = 'visible' and exists (select 1 from public.blugbug_posts p where p.id = post_id and p.status = 'published'))
    or user_id = (select blugbug_private.current_profile_id())
    or (select blugbug_private.is_admin())
  );
create policy "blugbug_comments_owner_insert" on public.blugbug_comments for insert to authenticated
  with check (
    user_id = (select blugbug_private.current_profile_id())
    and exists (
      select 1 from public.blugbug_posts p
      where p.id = post_id
        and (p.status = 'published' or p.user_id = (select blugbug_private.current_profile_id()))
        and (p.reply_permission = 'everyone'
          or (p.reply_permission = 'followers' and exists (
            select 1 from public.blugbug_follows f
            where f.follower_id = (select blugbug_private.current_profile_id()) and f.followed_id = p.user_id
          ))
          or p.user_id = (select blugbug_private.current_profile_id()))
    )
  );
create policy "blugbug_comments_owner_update" on public.blugbug_comments for update to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()))
  with check (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_comments_owner_delete" on public.blugbug_comments for delete to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_replies_public_read" on public.blugbug_comment_replies for select to anon, authenticated
  using (
    (status = 'visible' and exists (
      select 1 from public.blugbug_comments c
      join public.blugbug_posts p on p.id = c.post_id
      where c.id = comment_id and c.status = 'visible' and p.status = 'published'
    ))
    or user_id = (select blugbug_private.current_profile_id())
    or (select blugbug_private.is_admin())
  );
create policy "blugbug_replies_owner_insert" on public.blugbug_comment_replies for insert to authenticated
  with check (
    user_id = (select blugbug_private.current_profile_id())
    and exists (
      select 1 from public.blugbug_comments c
      join public.blugbug_posts p on p.id = c.post_id
      where c.id = comment_id and c.status = 'visible' and p.status = 'published'
        and (p.reply_permission = 'everyone'
          or (p.reply_permission = 'followers' and exists (
            select 1 from public.blugbug_follows f
            where f.follower_id = (select blugbug_private.current_profile_id()) and f.followed_id = p.user_id
          ))
          or p.user_id = (select blugbug_private.current_profile_id()))
    )
  );
create policy "blugbug_replies_owner_update" on public.blugbug_comment_replies for update to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()))
  with check (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_replies_owner_delete" on public.blugbug_comment_replies for delete to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_questions_public_read" on public.blugbug_paragraph_questions for select to anon, authenticated
  using (
    exists (select 1 from public.blugbug_posts p where p.id = post_id and p.status = 'published')
    or user_id = (select blugbug_private.current_profile_id())
    or (select blugbug_private.is_admin())
  );
create policy "blugbug_questions_owner_insert" on public.blugbug_paragraph_questions for insert to authenticated
  with check (
    user_id = (select blugbug_private.current_profile_id())
    and exists (select 1 from public.blugbug_posts p where p.id = post_id and p.status = 'published')
  );
create policy "blugbug_questions_owner_update" on public.blugbug_paragraph_questions for update to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()))
  with check (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_questions_owner_delete" on public.blugbug_paragraph_questions for delete to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_answers_public_read" on public.blugbug_paragraph_answers for select to anon, authenticated
  using (
    exists (
      select 1 from public.blugbug_paragraph_questions q
      join public.blugbug_posts p on p.id = q.post_id
      where q.id = question_id and p.status = 'published'
    )
    or user_id = (select blugbug_private.current_profile_id())
    or (select blugbug_private.is_admin())
  );
create policy "blugbug_answers_author_insert" on public.blugbug_paragraph_answers for insert to authenticated
  with check (
    user_id = (select blugbug_private.current_profile_id())
    and exists (
      select 1 from public.blugbug_paragraph_questions q
      join public.blugbug_posts p on p.id = q.post_id
      where q.id = question_id and p.user_id = (select blugbug_private.current_profile_id())
    )
    or (select blugbug_private.is_admin())
  );
create policy "blugbug_answers_author_update" on public.blugbug_paragraph_answers for update to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()))
  with check (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));

-- Private activity and support
create policy "blugbug_notifications_recipient_read" on public.blugbug_notifications for select to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_notifications_recipient_update" on public.blugbug_notifications for update to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()))
  with check (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_support_cases_member_read" on public.blugbug_support_cases for select to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_support_cases_owner_insert" on public.blugbug_support_cases for insert to authenticated
  with check (user_id = (select blugbug_private.current_profile_id()));
create policy "blugbug_support_cases_member_update" on public.blugbug_support_cases for update to authenticated
  using (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()))
  with check (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_support_messages_member_read" on public.blugbug_support_messages for select to authenticated
  using (exists (
    select 1 from public.blugbug_support_cases c
    where c.id = case_id and (c.user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()))
  ));
create policy "blugbug_support_messages_member_insert" on public.blugbug_support_messages for insert to authenticated
  with check (
    (user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()))
    and exists (
      select 1 from public.blugbug_support_cases c
      where c.id = case_id
        and (c.user_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()))
    )
  );
create policy "blugbug_blocks_owner_all" on public.blugbug_blocks for all to authenticated
  using (blocker_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()))
  with check (blocker_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_reports_owner_insert" on public.blugbug_reports for insert to authenticated
  with check (reporter_id = (select blugbug_private.current_profile_id()));
create policy "blugbug_reports_owner_or_admin_read" on public.blugbug_reports for select to authenticated
  using (reporter_id = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()));
create policy "blugbug_reports_admin_update" on public.blugbug_reports for update to authenticated
  using ((select blugbug_private.is_admin())) with check ((select blugbug_private.is_admin()));

-- GRANTS ---------------------------------------------------------------------

grant select on public.blugbug_users, public.blugbug_topics, public.blugbug_user_interests,
  public.blugbug_series, public.blugbug_posts, public.blugbug_follows,
  public.blugbug_post_likes, public.blugbug_comments, public.blugbug_comment_replies,
  public.blugbug_paragraph_questions, public.blugbug_paragraph_answers to anon, authenticated;

grant insert on public.blugbug_users to authenticated;
grant delete on public.blugbug_users to authenticated;
grant update (username, chatter_name, full_name, about_me, profile_image_url, header_image_url, updated_at)
  on public.blugbug_users to authenticated;
grant select, insert, update, delete on public.blugbug_topics, public.blugbug_user_interests,
  public.blugbug_series, public.blugbug_posts, public.blugbug_follows,
  public.blugbug_post_likes, public.blugbug_bookmarks, public.blugbug_post_shares,
  public.blugbug_comments, public.blugbug_comment_replies,
  public.blugbug_paragraph_questions, public.blugbug_paragraph_answers,
  public.blugbug_support_cases, public.blugbug_support_messages,
  public.blugbug_blocks, public.blugbug_reports to authenticated;
grant select, update (read) on public.blugbug_notifications to authenticated;
grant usage, select on sequence public.blugbug_topics_id_seq to anon, authenticated;

revoke all on public.blugbug_admins, public.blugbug_legacy_accounts,
  public.blugbug_recovery_requests from anon, authenticated;

-- UPDATED-AT TRIGGERS --------------------------------------------------------

drop trigger if exists blugbug_users_touch_updated_at on public.blugbug_users;
create trigger blugbug_users_touch_updated_at before update on public.blugbug_users
  for each row execute function blugbug_private.touch_updated_at();
drop trigger if exists blugbug_series_touch_updated_at on public.blugbug_series;
create trigger blugbug_series_touch_updated_at before update on public.blugbug_series
  for each row execute function blugbug_private.touch_updated_at();
drop trigger if exists blugbug_posts_touch_updated_at on public.blugbug_posts;
create trigger blugbug_posts_touch_updated_at before update on public.blugbug_posts
  for each row execute function blugbug_private.touch_updated_at();
drop trigger if exists blugbug_posts_prepare on public.blugbug_posts;
create trigger blugbug_posts_prepare before insert or update on public.blugbug_posts
  for each row execute function blugbug_private.prepare_post();
drop trigger if exists blugbug_comments_touch_updated_at on public.blugbug_comments;
create trigger blugbug_comments_touch_updated_at before update on public.blugbug_comments
  for each row execute function blugbug_private.touch_updated_at();
drop trigger if exists blugbug_replies_touch_updated_at on public.blugbug_comment_replies;
create trigger blugbug_replies_touch_updated_at before update on public.blugbug_comment_replies
  for each row execute function blugbug_private.touch_updated_at();
drop trigger if exists blugbug_questions_touch_updated_at on public.blugbug_paragraph_questions;
create trigger blugbug_questions_touch_updated_at before update on public.blugbug_paragraph_questions
  for each row execute function blugbug_private.touch_updated_at();
drop trigger if exists blugbug_answers_touch_updated_at on public.blugbug_paragraph_answers;
create trigger blugbug_answers_touch_updated_at before update on public.blugbug_paragraph_answers
  for each row execute function blugbug_private.touch_updated_at();
drop trigger if exists blugbug_support_cases_touch_updated_at on public.blugbug_support_cases;
create trigger blugbug_support_cases_touch_updated_at before update on public.blugbug_support_cases
  for each row execute function blugbug_private.touch_updated_at();
drop trigger if exists blugbug_reports_touch_updated_at on public.blugbug_reports;
create trigger blugbug_reports_touch_updated_at before update on public.blugbug_reports
  for each row execute function blugbug_private.touch_updated_at();

-- STORAGE BUCKETS ------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('blugbug_profiles', 'blugbug_profiles', true, 2097152, array['image/jpeg','image/png','image/webp','image/gif']),
  ('blugbug_headers', 'blugbug_headers', true, 5242880, array['image/jpeg','image/png','image/webp','image/gif']),
  ('blugbug_post_covers', 'blugbug_post_covers', true, 5242880, array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "blugbug_storage_public_read" on storage.objects
  for select to anon, authenticated
  using (bucket_id in ('blugbug_profiles','blugbug_headers','blugbug_post_covers'));
create policy "blugbug_storage_owner_insert" on storage.objects
  for insert to authenticated
  with check (
    bucket_id in ('blugbug_profiles','blugbug_headers','blugbug_post_covers')
    and (
      (storage.foldername(name))[1] = (select blugbug_private.current_profile_id())
      or (select blugbug_private.is_admin())
    )
  );
create policy "blugbug_storage_owner_update" on storage.objects
  for update to authenticated
  using (
    bucket_id in ('blugbug_profiles','blugbug_headers','blugbug_post_covers')
    and ((storage.foldername(name))[1] = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()))
  )
  with check (
    bucket_id in ('blugbug_profiles','blugbug_headers','blugbug_post_covers')
    and ((storage.foldername(name))[1] = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()))
  );
create policy "blugbug_storage_owner_delete" on storage.objects
  for delete to authenticated
  using (
    bucket_id in ('blugbug_profiles','blugbug_headers','blugbug_post_covers')
    and ((storage.foldername(name))[1] = (select blugbug_private.current_profile_id()) or (select blugbug_private.is_admin()))
  );

commit;

-- AFTER your administrator signs up through Supabase Auth, run this separately
-- in SQL Editor, replacing the placeholder with that account's auth.users UUID:
-- insert into public.blugbug_admins (auth_user_id)
-- values ('00000000-0000-0000-0000-000000000000') on conflict do nothing;
